services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ../services/user-service
    ports:
      - "5001:5001"
    environment:
      MONGO_URL: mongodb://root:example@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb

  media-service:
    build: ../services/media-service
    ports:
      - "5000:5000"
    environment:
      MONGO_URL: mongodb://root:example@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
      - user-service

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../frontend:/usr/share/nginx/html
    depends_on:
      - user-service
      - media-service

volumes:
  mongo_data: